export interface IDepartment {
    _id?: string;  // Optional since MongoDB will generate the ID
    name: string;
    description?: string;
    organizationId: string; // Refers to the organization that the department belongs to
    courses: string[];      // Array of course IDs
    teachers: string[];     // Array of teacher IDs
    classes: string[];      // Array of class IDs
    createdAt?: Date;       // Automatically generated by Mongoose with timestamps
    updatedAt?: Date;       // Automatically generated by Mongoose with timestamps
}


export interface IDepartmentApiResponseData<T> {
    departments: T;
    totalDepartments: number;
    limit: number;
    page: number;
    totalPages: number;
    serialNumberStartFrom: number;
    hasPrevPage: boolean;
    hasNextPage: boolean;
    prevPage: number | null;
    nextPage: number | null;
}

export interface IDepartmentApiResponse<T> {
    statusCode: number;
    data: IDepartmentApiResponseData<T>;
    message: string;
    success: boolean;
}